In [6]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""util functions"""

import numpy as np
from math import *

In [22]:
# Rotation Matrices

In [ ]:
class rMatrices:

In [14]:
    def __init__(self):
        self.data = []

In [15]:
    def rotx(theta):
        R =  np.array([[cos(theta), -sin(theta), 0],[sin(theta), cos(theta), 0],[0, 0, 1]])
        return R

In [23]:
    def roty(theta):
        R =  np.array([[cos(theta), 0, sin(theta)],[0,1,0],[-sin(theta),0,cos(theta)]])
        return R

In [17]:
    def rotz(theta):
        R =  np.array([[cos(theta), -sin(theta), 0],[sin(theta), cos(theta), 0],[0, 0, 1]])
        return R

In [24]:
rotx(0)

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
roty(0)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [26]:
rotz(0)

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])